LANG_NAMES = {
    "uz": "🇺🇿 O'zbekcha", "ru": "🇷🇺 Русский", "en": "🇬🇧 English",
    "tr": "🇹🇷 Türkçe", "ar": "🇸🇦 العربية", "es": "🇪🇸 Español",
    "fr": "🇫🇷 Français", "de": "🇩🇪 Deutsch", "hi": "🇮🇳 हिन्दी",
    "id": "🇮🇩 Indonesia", "kk": "🇰🇿 Қазақша", "tg": "🇹🇯 Тоҷикӣ",
    "fa": "🇮🇷 فارسی",
}

def _inf(h, m):
    return f"🚀 <b>{h}</b>\n\n🔴 YouTube\n📸 Instagram\n🎵 TikTok\n📘 Facebook\n🎶 {m}"

T = {}

T["uz"] = dict(
    welcome="👋 <b>Xush kelibsiz!</b>\n\n📥 YouTube, Instagram, TikTok, Facebook havolasini yuboring — video yoki MP3 qilib beraman.\n🎵 Yoki qo'shiq nomini yozing.",
    select_lang="🌐 <b>Tilni tanlang:</b>",
    lang_ok="✅ Til o'zgartirildi!",
    ask_search="🔍 Qo'shiq nomi yoki ijrochini yozing:",
    searching="🔎 <b>Qidirilmoqda...</b>",
    loading="⏳ <b>Tayyorlanmoqda...</b>",
    uploading="📤 <b>Yuborilmoqda...</b>",
    none="❌ Hech narsa topilmadi.",
    err="⚠️ <b>Xatolik:</b> ",
    too_big="⚠️ Fayl 50 MB dan katta. Pastroq sifat yoki MP3 tanlang.",
    choose="Nimani yuklab olay?",
    found="🎵 <b>«{q}»</b> bo'yicha natijalar:",
    b_search="🔍 Musiqa qidirish", b_lang="🌐 Til", b_info="ℹ️ Xizmatlar", b_stats="📊 Statistika",
    info=_inf("Qo'llab-quvvatlanadi:", "Musiqa qidiruv"),
    stats="📊 Yuklab olganlaringiz: <b>{n}</b>",
    video="🎬 Video", audio="🎵 MP3",
    expired="⏱ Havolani qaytadan yuboring",
)

T["ru"] = dict(
    welcome="👋 <b>Добро пожаловать!</b>\n\n📥 Пришлите ссылку на YouTube, Instagram, TikTok, Facebook — скачаю видео или MP3.\n🎵 Или напишите название песни.",
    select_lang="🌐 <b>Выберите язык:</b>",
    lang_ok="✅ Язык изменён!",
    ask_search="🔍 Введите название песни или исполнителя:",
    searching="🔎 <b>Поиск...</b>",
    loading="⏳ <b>Подготовка...</b>",
    uploading="📤 <b>Отправка...</b>",
    none="❌ Ничего не найдено.",
    err="⚠️ <b>Ошибка:</b> ",
    too_big="⚠️ Файл больше 50 МБ. Выберите качество ниже или MP3.",
    choose="Что скачать?",
    found="🎵 Результаты по <b>«{q}»</b>:",
    b_search="🔍 Поиск музыки", b_lang="🌐 Язык", b_info="ℹ️ Сервисы", b_stats="📊 Статистика",
    info=_inf("Поддерживается:", "Поиск музыки"),
    stats="📊 Вы скачали: <b>{n}</b>",
    video="🎬 Видео", audio="🎵 MP3",
    expired="⏱ Отправьте ссылку заново",
)

T["en"] = dict(
    welcome="👋 <b>Welcome!</b>\n\n📥 Send a YouTube, Instagram, TikTok or Facebook link — I'll download it as video or MP3.\n🎵 Or type a song name.",
    select_lang="🌐 <b>Choose language:</b>",
    lang_ok="✅ Language changed!",
    ask_search="🔍 Enter song title or artist:",
    searching="🔎 <b>Searching...</b>",
    loading="⏳ <b>Preparing...</b>",
    uploading="📤 <b>Uploading...</b>",
    none="❌ Nothing found.",
    err="⚠️ <b>Error:</b> ",
    too_big="⚠️ File is over 50 MB. Pick a lower quality or MP3.",
    choose="What should I download?",
    found="🎵 Results for <b>«{q}»</b>:",
    b_search="🔍 Search Music", b_lang="🌐 Language", b_info="ℹ️ Services", b_stats="📊 Stats",
    info=_inf("Supported:", "Music search"),
    stats="📊 Your downloads: <b>{n}</b>",
    video="🎬 Video", audio="🎵 MP3",
    expired="⏱ Please send the link again",
)

T["tr"] = dict(
    welcome="👋 <b>Hoş geldiniz!</b>\n\n📥 YouTube, Instagram, TikTok, Facebook bağlantısı gönderin — video veya MP3 olarak indireyim.\n🎵 Ya da şarkı adını yazın.",
    select_lang="🌐 <b>Dil seçin:</b>",
    lang_ok="✅ Dil değiştirildi!",
    ask_search="🔍 Şarkı adını veya sanatçıyı yazın:",
    searching="🔎 <b>Aranıyor...</b>",
    loading="⏳ <b>Hazırlanıyor...</b>",
    uploading="📤 <b>Gönderiliyor...</b>",
    none="❌ Hiçbir şey bulunamadı.",
    err="⚠️ <b>Hata:</b> ",
    too_big="⚠️ Dosya 50 MB'dan büyük. Daha düşük kalite veya MP3 seçin.",
    choose="Ne indireyim?",
    found="🎵 <b>«{q}»</b> sonuçları:",
    b_search="🔍 Müzik ara", b_lang="🌐 Dil", b_info="ℹ️ Servisler", b_stats="📊 İstatistik",
    info=_inf("Desteklenenler:", "Müzik arama"),
    stats="📊 İndirdikleriniz: <b>{n}</b>",
    video="🎬 Video", audio="🎵 MP3",
    expired="⏱ Bağlantıyı tekrar gönderin",
)

T["ar"] = dict(
    welcome="👋 <b>أهلاً بك!</b>\n\n📥 أرسل رابط YouTube أو Instagram أو TikTok أو Facebook وسأحمّله كفيديو أو MP3.\n🎵 أو اكتب اسم الأغنية.",
    select_lang="🌐 <b>اختر اللغة:</b>",
    lang_ok="✅ تم تغيير اللغة!",
    ask_search="🔍 اكتب اسم الأغنية أو الفنان:",
    searching="🔎 <b>جارٍ البحث...</b>",
    loading="⏳ <b>جارٍ التحضير...</b>",
    uploading="📤 <b>جارٍ الإرسال...</b>",
    none="❌ لم يتم العثور على شيء.",
    err="⚠️ <b>خطأ:</b> ",
    too_big="⚠️ الملف أكبر من 50 ميغابايت. اختر جودة أقل أو MP3.",
    choose="ماذا أحمّل؟",
    found="🎵 نتائج <b>«{q}»</b>:",
    b_search="🔍 بحث عن موسيقى", b_lang="🌐 اللغة", b_info="ℹ️ الخدمات", b_stats="📊 الإحصائيات",
    info=_inf("المدعوم:", "البحث عن الموسيقى"),
    stats="📊 عدد تحميلاتك: <b>{n}</b>",
    video="🎬 فيديو", audio="🎵 MP3",
    expired="⏱ أعد إرسال الرابط",
)

T["es"] = dict(
    welcome="👋 <b>¡Bienvenido!</b>\n\n📥 Envía un enlace de YouTube, Instagram, TikTok o Facebook y lo descargo en video o MP3.\n🎵 O escribe el nombre de una canción.",
    select_lang="🌐 <b>Elige el idioma:</b>",
    lang_ok="✅ ¡Idioma cambiado!",
    ask_search="🔍 Escribe el título o el artista:",
    searching="🔎 <b>Buscando...</b>",
    loading="⏳ <b>Preparando...</b>",
    uploading="📤 <b>Enviando...</b>",
    none="❌ No se encontró nada.",
    err="⚠️ <b>Error:</b> ",
    too_big="⚠️ El archivo supera 50 MB. Elige menor calidad o MP3.",
    choose="¿Qué descargo?",
    found="🎵 Resultados para <b>«{q}»</b>:",
    b_search="🔍 Buscar música", b_lang="🌐 Idioma", b_info="ℹ️ Servicios", b_stats="📊 Estadísticas",
    info=_inf("Compatible con:", "Búsqueda de música"),
    stats="📊 Tus descargas: <b>{n}</b>",
    video="🎬 Video", audio="🎵 MP3",
    expired="⏱ Envía el enlace de nuevo",
)

T["fr"] = dict(
    welcome="👋 <b>Bienvenue !</b>\n\n📥 Envoyez un lien YouTube, Instagram, TikTok ou Facebook et je le télécharge en vidéo ou MP3.\n🎵 Ou écrivez le nom d'une chanson.",
    select_lang="🌐 <b>Choisissez la langue :</b>",
    lang_ok="✅ Langue modifiée !",
    ask_search="🔍 Entrez le titre ou l'artiste :",
    searching="🔎 <b>Recherche...</b>",
    loading="⏳ <b>Préparation...</b>",
    uploading="📤 <b>Envoi...</b>",
    none="❌ Aucun résultat.",
    err="⚠️ <b>Erreur :</b> ",
    too_big="⚠️ Fichier de plus de 50 Mo. Choisissez une qualité inférieure ou MP3.",
    choose="Que télécharger ?",
    found="🎵 Résultats pour <b>«{q}»</b> :",
    b_search="🔍 Chercher de la musique", b_lang="🌐 Langue", b_info="ℹ️ Services", b_stats="📊 Statistiques",
    info=_inf("Pris en charge :", "Recherche de musique"),
    stats="📊 Vos téléchargements : <b>{n}</b>",
    video="🎬 Vidéo", audio="🎵 MP3",
    expired="⏱ Renvoyez le lien",
)

T["de"] = dict(
    welcome="👋 <b>Willkommen!</b>\n\n📥 Sende einen Link von YouTube, Instagram, TikTok oder Facebook – ich lade ihn als Video oder MP3 herunter.\n🎵 Oder schreibe einen Songnamen.",
    select_lang="🌐 <b>Sprache wählen:</b>",
    lang_ok="✅ Sprache geändert!",
    ask_search="🔍 Songtitel oder Künstler eingeben:",
    searching="🔎 <b>Suche läuft...</b>",
    loading="⏳ <b>Wird vorbereitet...</b>",
    uploading="📤 <b>Wird gesendet...</b>",
    none="❌ Nichts gefunden.",
    err="⚠️ <b>Fehler:</b> ",
    too_big="⚠️ Datei größer als 50 MB. Wähle niedrigere Qualität oder MP3.",
    choose="Was soll ich herunterladen?",
    found="🎵 Ergebnisse für <b>«{q}»</b>:",
    b_search="🔍 Musik suchen", b_lang="🌐 Sprache", b_info="ℹ️ Dienste", b_stats="📊 Statistik",
    info=_inf("Unterstützt:", "Musiksuche"),
    stats="📊 Deine Downloads: <b>{n}</b>",
    video="🎬 Video", audio="🎵 MP3",
    expired="⏱ Sende den Link erneut",
)

T["hi"] = dict(
    welcome="👋 <b>स्वागत है!</b>\n\n📥 YouTube, Instagram, TikTok या Facebook का लिंक भेजें — मैं वीडियो या MP3 डाउनलोड कर दूँगा।\n🎵 या गाने का नाम लिखें।",
    select_lang="🌐 <b>भाषा चुनें:</b>",
    lang_ok="✅ भाषा बदल गई!",
    ask_search="🔍 गाने का नाम या कलाकार लिखें:",
    searching="🔎 <b>खोज रहा हूँ...</b>",
    loading="⏳ <b>तैयार हो रहा है...</b>",
    uploading="📤 <b>भेजा जा रहा है...</b>",
    none="❌ कुछ नहीं मिला।",
    err="⚠️ <b>त्रुटि:</b> ",
    too_big="⚠️ फ़ाइल 50 MB से बड़ी है। कम क्वालिटी या MP3 चुनें।",
    choose="क्या डाउनलोड करूँ?",
    found="🎵 <b>«{q}»</b> के परिणाम:",
    b_search="🔍 संगीत खोजें", b_lang="🌐 भाषा", b_info="ℹ️ सेवाएँ", b_stats="📊 आँकड़े",
    info=_inf("समर्थित:", "संगीत खोज"),
    stats="📊 आपके डाउनलोड: <b>{n}</b>",
    video="🎬 वीडियो", audio="🎵 MP3",
    expired="⏱ लिंक दोबारा भेजें",
)

T["id"] = dict(
    welcome="👋 <b>Selamat datang!</b>\n\n📥 Kirim tautan YouTube, Instagram, TikTok, atau Facebook — saya unduh sebagai video atau MP3.\n🎵 Atau ketik judul lagu.",
    select_lang="🌐 <b>Pilih bahasa:</b>",
    lang_ok="✅ Bahasa diubah!",
    ask_search="🔍 Ketik judul lagu atau nama artis:",
    searching="🔎 <b>Mencari...</b>",
    loading="⏳ <b>Menyiapkan...</b>",
    uploading="📤 <b>Mengirim...</b>",
    none="❌ Tidak ditemukan.",
    err="⚠️ <b>Kesalahan:</b> ",
    too_big="⚠️ File lebih dari 50 MB. Pilih kualitas lebih rendah atau MP3.",
    choose="Unduh apa?",
    found="🎵 Hasil untuk <b>«{q}»</b>:",
    b_search="🔍 Cari musik", b_lang="🌐 Bahasa", b_info="ℹ️ Layanan", b_stats="📊 Statistik",
    info=_inf("Didukung:", "Pencarian musik"),
    stats="📊 Unduhan Anda: <b>{n}</b>",
    video="🎬 Video", audio="🎵 MP3",
    expired="⏱ Kirim ulang tautannya",
)

T["kk"] = dict(
    welcome="👋 <b>Қош келдіңіз!</b>\n\n📥 YouTube, Instagram, TikTok немесе Facebook сілтемесін жіберіңіз — видео немесе MP3 етіп жүктеп беремін.\n🎵 Немесе ән атауын жазыңыз.",
    select_lang="🌐 <b>Тілді таңдаңыз:</b>",
    lang_ok="✅ Тіл өзгертілді!",
    ask_search="🔍 Ән атауын немесе орындаушыны жазыңыз:",
    searching="🔎 <b>Іздеуде...</b>",
    loading="⏳ <b>Дайындалуда...</b>",
    uploading="📤 <b>Жіберілуде...</b>",
    none="❌ Ештеңе табылмады.",
    err="⚠️ <b>Қате:</b> ",
    too_big="⚠️ Файл 50 МБ-тан үлкен. Төмен сапаны немесе MP3 таңдаңыз.",
    choose="Нені жүктейін?",
    found="🎵 <b>«{q}»</b> нәтижелері:",
    b_search="🔍 Музыка іздеу", b_lang="🌐 Тіл", b_info="ℹ️ Қызметтер", b_stats="📊 Статистика",
    info=_inf("Қолдау көрсетіледі:", "Музыка іздеу"),
    stats="📊 Сіздің жүктеулер: <b>{n}</b>",
    video="🎬 Видео", audio="🎵 MP3",
    expired="⏱ Сілтемені қайта жіберіңіз",
)

T["tg"] = dict(
    welcome="👋 <b>Хуш омадед!</b>\n\n📥 Истиноди YouTube, Instagram, TikTok ё Facebook-ро фиристед — ман онро ҳамчун видео ё MP3 зеркашӣ мекунам.\n🎵 Ё номи сурудро нависед.",
    select_lang="🌐 <b>Забонро интихоб кунед:</b>",
    lang_ok="✅ Забон иваз шуд!",
    ask_search="🔍 Номи суруд ё ҳунармандро нависед:",
    searching="🔎 <b>Ҷустуҷӯ...</b>",
    loading="⏳ <b>Омода мешавад...</b>",
    uploading="📤 <b>Фиристода мешавад...</b>",
    none="❌ Чизе ёфт нашуд.",
    err="⚠️ <b>Хато:</b> ",
    too_big="⚠️ Файл аз 50 МБ калон аст. Сифати пасттар ё MP3 интихоб кунед.",
    choose="Чиро зеркашӣ кунам?",
    found="🎵 Натиҷаҳо барои <b>«{q}»</b>:",
    b_search="🔍 Ҷустуҷӯи мусиқӣ", b_lang="🌐 Забон", b_info="ℹ️ Хидматҳо", b_stats="📊 Омор",
    info=_inf("Дастгирӣ мешавад:", "Ҷустуҷӯи мусиқӣ"),
    stats="📊 Зеркашиҳои шумо: <b>{n}</b>",
    video="🎬 Видео", audio="🎵 MP3",
    expired="⏱ Истинодро дубора фиристед",
)

T["fa"] = dict(
    welcome="👋 <b>خوش آمدید!</b>\n\n📥 لینک YouTube، Instagram، TikTok یا Facebook را بفرستید تا به صورت ویدیو یا MP3 دانلود کنم.\n🎵 یا نام آهنگ را بنویسید.",
    select_lang="🌐 <b>زبان را انتخاب کنید:</b>",
    lang_ok="✅ زبان تغییر کرد!",
    ask_search="🔍 نام آهنگ یا خواننده را بنویسید:",
    searching="🔎 <b>در حال جستجو...</b>",
    loading="⏳ <b>در حال آماده‌سازی...</b>",
    uploading="📤 <b>در حال ارسال...</b>",
    none="❌ چیزی پیدا نشد.",
    err="⚠️ <b>خطا:</b> ",
    too_big="⚠️ حجم فایل بیش از ۵۰ مگابایت است. کیفیت پایین‌تر یا MP3 را انتخاب کنید.",
    choose="چه چیزی دانلود کنم؟",
    found="🎵 نتایج برای <b>«{q}»</b>:",
    b_search="🔍 جستجوی موزیک", b_lang="🌐 زبان", b_info="ℹ️ سرویس‌ها", b_stats="📊 آمار",
    info=_inf("پشتیبانی می‌شود:", "جستجوی موزیک"),
    stats="📊 دانلودهای شما: <b>{n}</b>",
    video="🎬 ویدیو", audio="🎵 MP3",
    expired="⏱ لینک را دوباره بفرستید",
)
